version: "3"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=carteiraVirtual
    ports:
      - "5432:5432"
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: carteira-virtual-app
    links:
      - "postgres-db"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres-db
    networks:
      - default

networks:
  default:
