version: "3"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql
    networks:
      - default
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: carteira-virtual-app
    links:
      - "postgres-db"
    restart: always
    env_file: ./.env
    environment:
      - "PORT=${PORT}"
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres-db
    networks:
      - default

networks:
  default:

volumes:
  dbdata: