version: "3"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: carteira-virtual-app
    links:
      - "postgres-db"
    restart: always
    env_file: .env
    environment:
      - DB=${DB}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${PORT}
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres-db
    networks:
      - default

networks:
  default:

volumes:
  dbdata:
